//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CINQWCFHostWPF.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IComponentManager")]
    public interface IComponentManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComponentManager/ReadData", ReplyAction="http://tempuri.org/IComponentManager/ReadDataResponse")]
        CINQWCF.Service.PersonalData[] ReadData();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IComponentManager/ReadData", ReplyAction="http://tempuri.org/IComponentManager/ReadDataResponse")]
        System.IAsyncResult BeginReadData(System.AsyncCallback callback, object asyncState);
        
        CINQWCF.Service.PersonalData[] EndReadData(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IComponentManagerChannel : CINQWCFHostWPF.ServiceReference1.IComponentManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReadDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ReadDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public CINQWCF.Service.PersonalData[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((CINQWCF.Service.PersonalData[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ComponentManagerClient : System.ServiceModel.ClientBase<CINQWCFHostWPF.ServiceReference1.IComponentManager>, CINQWCFHostWPF.ServiceReference1.IComponentManager {
        
        private BeginOperationDelegate onBeginReadDataDelegate;
        
        private EndOperationDelegate onEndReadDataDelegate;
        
        private System.Threading.SendOrPostCallback onReadDataCompletedDelegate;
        
        public ComponentManagerClient() {
        }
        
        public ComponentManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ComponentManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComponentManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComponentManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<ReadDataCompletedEventArgs> ReadDataCompleted;
        
        public CINQWCF.Service.PersonalData[] ReadData() {
            return base.Channel.ReadData();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginReadData(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginReadData(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public CINQWCF.Service.PersonalData[] EndReadData(System.IAsyncResult result) {
            return base.Channel.EndReadData(result);
        }
        
        private System.IAsyncResult OnBeginReadData(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginReadData(callback, asyncState);
        }
        
        private object[] OnEndReadData(System.IAsyncResult result) {
            CINQWCF.Service.PersonalData[] retVal = this.EndReadData(result);
            return new object[] {
                    retVal};
        }
        
        private void OnReadDataCompleted(object state) {
            if ((this.ReadDataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ReadDataCompleted(this, new ReadDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ReadDataAsync() {
            this.ReadDataAsync(null);
        }
        
        public void ReadDataAsync(object userState) {
            if ((this.onBeginReadDataDelegate == null)) {
                this.onBeginReadDataDelegate = new BeginOperationDelegate(this.OnBeginReadData);
            }
            if ((this.onEndReadDataDelegate == null)) {
                this.onEndReadDataDelegate = new EndOperationDelegate(this.OnEndReadData);
            }
            if ((this.onReadDataCompletedDelegate == null)) {
                this.onReadDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnReadDataCompleted);
            }
            base.InvokeAsync(this.onBeginReadDataDelegate, null, this.onEndReadDataDelegate, this.onReadDataCompletedDelegate, userState);
        }
    }
}
